DELIMITER //
DROP PROCEDURE IF EXISTS SP_GET_PRODUCT_BY_CODE;
CREATE PROCEDURE SP_GET_PRODUCT_BY_CODE(IN cod VARCHAR(10))

BEGIN
 SELECT cod_produto FROM producto WHERE cod_produto = cod;
END //
DELIMITER ;